export const statusTypes: Record<string, { title: string; color: string }> = {
    pending: { title: "Pending", color: "#FA9411" },
    booked: { title: "Booked", color: "#FA9411" },
    awaiting_payment: { title: "Awaiting Payment", color: "#FA9411" },
    awaiting_admin_approval: { title: "Awaiting Admin Approval", color: "#FA9411" },
    pending_verification: { title: "Pending Verification", color: "#FA9411" },
    payment_pending: { title: "Payment Pending", color: "#FA9411" },
    approved: { title: "Approved", color: "#27AE60" },
    available: { title: "Available", color: "#27AE60" },
    completed: { title: "Completed", color: "#27AE60" },
    in_progress: { title: "In Progress", color: "#27AE60" },
    in_use: { title: "In Use", color: "#F03B13" },
    maintenance: { title: "Maintenance", color: "#FF0000" },
    rejected: { title: "Rejected", color: "#FE391E" },
    paid: { title: "Paid", color: "#27AE60" },
    cancelled: { title: "Cancelled", color: "#FE391E" },
    abandoned: { title: "Abandoned", color: "#FE391E" },
    verified: { title: "Verified", color: "#27AE60" },
    processing: { title: "Processing", color: "#FA9411" },
    success: { title: "Success", color: "#27AE60" },
    failed: { title: "Failed", color: "#27AE60" },
    refunded: { title: "Refunded", color: "#F03B13" },
  };
  

  export const statusOptions = [
    { value: "", label: "All Statuses" },
    { value: "pending", label: "Pending" },
    { value: "booked", label: "Booked" },
    { value: "awaiting_payment", label: "Awaiting Payment" },
    { value: "awaiting_admin_approval", label: "Awaiting Admin Approval" },
    { value: "pending_verification", label: "Pending Verification" },
    { value: "payment_pending", label: "Payment Pending" },
    { value: "approved", label: "Approved" },
    { value: "available", label: "Available" },
    { value: "completed", label: "Completed" },
    { value: "in_progress", label: "In Progress" },
    { value: "in_use", label: "In Use" },
    { value: "maintenance", label: "Maintenance" },
    { value: "rejected", label: "Rejected" },
    { value: "paid", label: "Paid" },
    { value: "cancelled", label: "Cancelled" },
    { value: "abandoned", label: "Abandoned" },
    { value: "verified", label: "Verified" },
    { value: "processing", label: "Processing" },
    { value: "success", label: "Success" },
    { value: "failed", label: "Failed" },
    { value: "refunded", label: "Refunded" },
  ];