import Image from "next/image";
import Link from "next/link";
import styles from "./tractracHomepage.module.css";
import { bindTitleOrphans } from "@/app/utils/bindTitleOrphans";

const DEFAULT_ISSAM_IMAGE =
  "https://api.tractrac.co/media/images/68ddc91c-940a-4fe8-92bf-7b8177746163.webp";

const ISSAM_IMAGE_SRC =
  process.env.NEXT_PUBLIC_TRACTRAC_ISSAM_IMAGE?.trim() || DEFAULT_ISSAM_IMAGE;

function FloatBriefcase({ stroke }: { stroke: string }) {
  return (
    
    <svg width="17" height="17" viewBox="0 0 17 17" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M8.5 8.5H8.5075" stroke-width="0.53125" stroke={stroke} stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M11.3346 4.24984V2.83317C11.3346 2.45745 11.1854 2.09711 10.9197 1.83144C10.654 1.56576 10.2937 1.4165 9.91797 1.4165H7.08464C6.70891 1.4165 6.34858 1.56576 6.0829 1.83144C5.81722 2.09711 5.66797 2.45745 5.66797 2.83317V4.24984" stroke={stroke} stroke-width="0.53125" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M15.5846 9.2085C13.4829 10.5961 11.0198 11.3358 8.5013 11.3358C5.98279 11.3358 3.51974 10.5961 1.41797 9.2085" stroke={stroke} stroke-width="0.53125" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M14.168 4.25H2.83464C2.05223 4.25 1.41797 4.88426 1.41797 5.66667V12.75C1.41797 13.5324 2.05223 14.1667 2.83464 14.1667H14.168C14.9504 14.1667 15.5846 13.5324 15.5846 12.75V5.66667C15.5846 4.88426 14.9504 4.25 14.168 4.25Z" stroke={stroke} stroke-width="0.53125" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    
  );
}

export default function TractracIssamSection() {
  return (
    <section id="issam-program" className={styles.issam} aria-labelledby="tractrac-issam-heading">
      <div className={styles.issamInner}>
        <div className={styles.issamGrid}>
          <div className={styles.issamCopy}>
            <p className={styles.issamTag}>
              The ISSAM Project, Mastercard
              Foundation
            </p>
            <h2 id="tractrac-issam-heading" className={styles.issamTitle}>
              {bindTitleOrphans("Empowering Youth, Women & Persons with Disabilities in Mechanization")}
            </h2>
            <div className={styles.issamBody}>
              <p>
                In partnership with the Mastercard Foundation, TracTrac launched ISSAM, a
                five-year program designed to unlock economic opportunities within the
                mechanization economy through a cooperative business model.
              </p>
              <p>
                Participants are trained, certified, and empowered to build their own mechanization
                service businesses across Nigeria.
              </p>
            </div>
            <Link href="/special-programs/issam" className={styles.issamCta}>
              Learn About ISSAM →
            </Link>
          </div>

          <div className={styles.issamVisual}>
            <Image
              src={ISSAM_IMAGE_SRC}
              alt="ISSAM participant operating mechanization equipment with a trainer"
              width={720}
              height={540}
              className={styles.issamImg}
              sizes="(max-width: 1023px) 100vw, 50vw"
            />
            <div className={`${styles.issamFloatCard} ${styles.issamFloatCardRevenue}`}>
              <div className={styles.issamFloatCardTop}>
                <span className={styles.issamPillPurple}>₦20M+</span>
                <span className={styles.issamFloatIcon}>
                  <FloatBriefcase stroke="#64748b" />
                </span>
              </div>
              <p className={styles.issamFloatLabel}>Revenue Generated by Cooperatives</p>
            </div>
            <div className={`${styles.issamFloatCard} ${styles.issamFloatCardBiz}`}>
              <div className={styles.issamFloatCardTop}>
                <span className={styles.issamPillGreen}>280+</span>
                <span className={styles.issamFloatIcon}>
                  <FloatBriefcase stroke="#16A34A" />
                </span>
              </div>
              <p className={styles.issamFloatLabel}>Cooperative Businesses Established</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
